version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: example_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080